version: "3.9"

services:

  postgres:
    image: postgres:15

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hospitaldb

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - hospital-network

    deploy:
      replicas: 1

  redis:
    image: redis:7

    networks:
      - hospital-network

    deploy:
      replicas: 1

  patient-service:
    image: venkat2708/hms:patient-service

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/hospitaldb

    networks:
      - hospital-network

    deploy:
      replicas: 2

  doctor-service:
    image: venkat2708/hms:doctor-service

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/hospitaldb

    networks:
      - hospital-network

    deploy:
      replicas: 2

  appointment-service:
    image: venkat2708/hms:appointment-service

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/hospitaldb

    networks:
      - hospital-network

    deploy:
      replicas: 2

  billing-service:
    image: venkat2708/hms:billing-service

    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/hospitaldb

    networks:
      - hospital-network

    deploy:
      replicas: 2

  api-gateway:
    image: venkat2708/hms:api-gateway

    ports:
      - "80:80"

    networks:
      - hospital-network

    deploy:
      replicas: 2

  frontend:
    image: venkat2708/hms:frontend

    ports:
      - "8080:80"

    networks:
      - hospital-network

    deploy:
      replicas: 2

volumes:
  postgres_data:

networks:
  hospital-network:
    driver: overlay
