events {}

http {

    upstream patient_service {
        server patient-service:5001;
    }

    upstream doctor_service {
        server doctor-service:5002;
    }

    upstream appointment_service {
        server appointment-service:5003;
    }

    upstream billing_service {
        server billing-service:5004;
    }

    upstream dashboard_service {
        server dashboard-service:5005;
    }

    server {

        listen 80;

        location /patients {
            proxy_pass http://patient_service;
        }

        location /doctors {
            proxy_pass http://doctor_service;
        }

        location /appointments {
            proxy_pass http://appointment_service;
        }

        location /bills {
            proxy_pass http://billing_service;
        }

        location /dashboard {
            proxy_pass http://dashboard_service;
        }
    }
}
